name: 'My Ruby Action'
description: 'A GitHub Action written in Ruby that processes input.'
inputs:
  github_token:
    description: 'GitHub Token'
    required: true
  pull_request_id:
    description: 'Pull Request ID'
    required: true
  github_base_ref:
    description: 'GitHub Base Reference'
    required: true

outputs:
  my_output:
    description: 'Output after processing'

runs:
  using: 'composite'
  steps:
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'

    - name: Install dependencies
      run: |
        gem install typocop
      shell: bash

    - name: Run Typocop
      run: |
        typocop execute
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        PULL_REQUEST_ID: ${{ inputs.pull_request_id }}
        GITHUB_BASE_REF: ${{ inputs.github_base_ref }}
      shell: bash
