name: 'My Ruby Action'
description: 'A GitHub Action written in Ruby that processes input.'
inputs:
  encoded_typo_outputs:
    description: 'Encoded Typo Ouputs'
    required: true
  github_token:
    description: 'GitHub Token'
    required: true
  pull_request_id:
    description: 'Pull Request ID'
    required: true

outputs:
  my_output:
    description: 'Output after processing'

runs:
  using: 'composite'
  steps:
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'

    - name: Install dependencies
      run: |
        gem install octokit json
      shell: bash

    - name: Run Typocop
      run: |
        ruby typocop.rb
      env:
        ENCODED_TYPO_OUTPUTS: ${{ inputs.encoded_typo_outputs }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        PULL_REQUEST_ID: ${{ inputs.pull_request_id }}
      shell: bash
