name: Check Typos in Pull Request

on: [pull_request]

jobs:
  check-typos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.14.0-alpha.1'

      - name: Install typos
        run: |
          python3 -m pip install --upgrade pip
          pip install typos

      - name: Get changed files
        id: changed-files
        run: |
          set -e
          echo "Listing changed files..."

          git fetch --all
          base_commit=$(git rev-parse origin/${{ github.base_ref }})
          current_commit=$(git rev-parse HEAD)
          echo "Base commit: $base_commit"
          echo "Current commit: $current_commit"

          changed_files=$(git diff --name-only $base_commit $current_commit || true)
          echo "Changed files: $changed_files"

          # If there are no changed files, set the environment variable to false
          if [ -z "$changed_files" ]; then
            echo "CHANGED_FILES=false" >> $GITHUB_ENV
          else
            echo "CHANGED_FILES=true" >> $GITHUB_ENV
            # Use newline-separated file list to avoid issues with special characters or spaces
            echo "$changed_files" | tr ' ' '\n' > changed_files.txt
            echo "CHANGED_FILE_LIST=changed_files.txt" >> $GITHUB_ENV
          fi

      - name: Check if files have changed
        id: check-files
        run: |
          if [ "${{ env.CHANGED_FILES }}" == "true" ]; then
            echo "Files have changed."
            echo "RUN_SCRIPTS=true" >> $GITHUB_ENV
          else
            echo "No files changed."
            echo "RUN_SCRIPTS=false" >> $GITHUB_ENV
          fi

      - name: Check typos in changed files
        if: ${{ env.RUN_SCRIPTS == 'true' }}
        run: |
          set -e
          echo "Checking typos in changed files..."

          # Read the list of changed files from the text file
          while IFS= read -r file; do
            echo "Checking typos in $file"
            typos check "$file"
          done < ${{ env.CHANGED_FILE_LIST }}

      - name: Comment on PR if typos found
        if: ${{ failure() }}
        uses: actions/github-script@v6
        with:
          script: |
            const { github } = require('@actions/github');
            const prNumber = github.context.payload.pull_request.number;
            const commentBody = '### Typos found in your Pull Request. Please review the changes!';
            await github.rest.issues.createComment({
              ...github.context.repo,
              issue_number: prNumber,
              body: commentBody,
            });
